
friend: 
  nomal:
    - こんにちは、name君元気？
    - name君は、レッドブルとモンスターどっち派？私はドクペかな
    - name君は、新型のMacBookProどう思う？　私？私はね……
    - name君の趣味は何？ 私は、絵を書くことかなー
    - 最近良くname君と会ってる気がするんだー
  worry:
    - 最近name君と会えてないなぁ・・・
    - name君無理してない？気をつけてね
  happy:
    - わぁ、name君おごってくれてありがとう！
    - 今日もおごってくれるの？name君って優しいんだね。
    - 今日見た映画面白かったね。ありがとう、name君
    - いつもおごってくれるけど、name君はちゃんと貯金してるのー？
  item:
    - 今日はネックレスつけてみたんだけど・・・どうかな？似合ってる？

girlfriend:
  nomal:
    - name君、次はどこに連れて行ってくれるの？私が行きたいところはねー……
    - name君が最近はまってるものはなに？　私もやってみようかなぁ
    - name君と一緒にいると楽しいからまた遊びたいなー
    - 最近はまってるアニメとかある？ おすすめ教えてほしいなぁ
    - かわいいお洋服見つけたのー似合ってるかなぁ？
  worry:
    - 最近name君忙しいのかなぁ・・・
    - name君のことだから無理してそうで心配かも・・・
  happy:
    - 今日も楽しかった、name君ありがと！
    - やっぱりname君と一緒に入れると嬉しいな！
  happy_worry:
    - おごってくれるの？嬉しいけどムリしないでねname君。
    - 久しぶりに会えて嬉しかった、がんばってねname君。
    - name君と会えるとやっぱり楽しいな、でも無理したらだめだよ〜
    - 最近name君、忙しそうだったけど大丈夫そうでよかった〜
  item:
    - きれいなネックレス・・・ありがとう大事にするね。
    - かわいいブレスレッドだね、ありがとう大切にするよ。
  end:
    - これまで幸せにしてくれてありがとうname君・・・いいえ、あ・な・た　♡
